# Generated by Django 3.1.6 on 2021-03-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='num_voters',
            field=models.PositiveIntegerField(default=0, verbose_name='# of voters'),
        ),
    ]
